services:
    _defaults:
        autowire: true
        autoconfigure: true

    Kazetenn\Admin\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Tests/'

    Kazetenn\Admin\Service\MenuHandler:
        arguments:
            $adminPages: '%kazetenn_admin.pages%'
            $authorizedRoles: '%kazetenn_admin.authorized_roles%'
            $defaultTranslationDomain: '%kazetenn_admin.translation_domain%'
            $menuEntries: '%kazetenn_admin.menu_entries%'

    Kazetenn\Admin\Service\PageHandler:
        calls:
            - setContainer: ['@service_container']
